# Possible Words From Phone Digits
# Difficulty: MediumAccuracy: 52.79%Submissions: 89K+Points: 4Average Time: 20m
# You are given a keypad (as shown in the diagram) and an array arr[ ] containing digits, your task is to list all possible words in any order which can be generated by pressing numbers in arr[] sequentially.

# Note: Number 0 and 1 do not map to any letters.
# You can return the words in any order, the driver code will print them in sorted order.



# Examples :

# Input: arr[] = [2, 3]
# Output: [ad, ae, af, bd, be, bf, cd, ce, cf]
# Explanation: When we press 2 and 3 total 3 x 3 = 9 possible words formed.
# Input: arr[] = [2]
# Output: [a, b, c]
# Explanation: When we press 2 total 3 possible words formed.
# Constraints:
# 1 ≤ arr.size() ≤ 9
# 0 ≤ arr[i] ≤ 9

# Expected Complexities
# Time Complexity: O(4 ^ n)
# Auxiliary Space: O(n)

class Solution:
    def possibleWords(self, arr):
        # code here
        keypad = {
            0: [],
            1: [],
            2: ['a','b','c'],
            3: ['d','e','f'],
            4: ['g','h','i'],
            5: ['j','k','l'],
            6: ['m','n','o'],
            7: ['p','q','r','s'],
            8: ['t','u','v'],
            9: ['w','x','y','z']
        }

        n = len(arr)
        if n == 0:
            return []

        # If any digit has no mapping (0 or 1), no words can be formed
        for d in arr:
            if d not in keypad or not keypad[d]:
                return []

        results = []

        def dfs(idx, path):
            if idx == n:
                results.append(''.join(path))
                return
            for ch in keypad[arr[idx]]:
                path.append(ch)
                dfs(idx + 1, path)
                path.pop()

        dfs(0, [])
        return results

sol = Solution()
print(sol.possibleWords([2,3]))  # Example usage
print(sol.possibleWords([2]))
print(sol.possibleWords([8,8,1]))  # Example with 0

